### ISSUE TITLE
OSError: [WinError 123] Again :/

### ISSUE THREAD

**Issue by CevreMuhendisi** [neuronalism/edxdlr#3]
Downloading Water and Wastewater Treatment Engineering: Biochemical Technology | 水处理工程：生物化学方法 [block-v1:TsinghuaX+40050455.2x+1T2021+type@course+block@course] sequentially
Output directory: Downloaded
Traceback (most recent call last):
  File "C:\Users\İbrahim\Desktop\Edx\edxdlr-master\edxdlr.py", line 689, in <module>
    main()
  File "C:\Users\İbrahim\Desktop\Edx\edxdlr-master\edxdlr.py", line 684, in main
    download_course(args, course_block, headers, file_formats)
  File "C:\Users\İbrahim\Desktop\Edx\edxdlr-master\edxdlr.py", line 636, in download_course
    mkdir_p(target_dir)
  File "C:\Users\İbrahim\Desktop\Edx\edxdlr-master\utils.py", line 133, in mkdir_p
    os.makedirs(path, mode)
  File "C:\Users\İbrahim\AppData\Local\Programs\Python\Python310\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\İbrahim\AppData\Local\Programs\Python\Python310\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\İbrahim\AppData\Local\Programs\Python\Python310\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\İbrahim\AppData\Local\Programs\Python\Python310\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] Dosya adı, dizin adı veya birim etiketi sözdizimi hatalı: 'Downloaded\\Water and Wastewater Treatment Engineering  Biochemical Technology | 水处理工程：生物化学方法'

Thanks for help

**Comment by neuronalism** [comment]
okay fixed in utils.py
now should avoid all WinError 123
